FIND_PATH(FREEIMAGE_INCLUDE_PATH FreeImage.h /usr/include /usr/local/include)
FIND_LIBRARY(FREEIMAGE_LIBRARY NAMES freeimage PATH /usr/lib ${LIBRARY_OUTPUT_PATH})

IF (FREEIMAGE_INCLUDE_DIR AND FREEIMAGE_LIBRARY)
   SET(FREEIMAGE_FOUND TRUE)
ENDIF (FREEIMAGE_INCLUDE_DIR AND FREEIMAGE_LIBRARY)


IF (FREEIMAGE_FOUND)
   IF (NOT FREEIMAGE_FIND_QUIETLY)
      MESSAGE(STATUS "Found FreeImage: ${FREEIMAGE_LIBRARY}")
   ENDIF (NOT FREEIMAGE_FIND_QUIETLY)
ELSE (FREEIMAGE_FOUND)
   IF (FREEIMAGE_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find FreeImage")
   ENDIF (FREEIMAGE_FIND_REQUIRED)
ENDIF (FREEIMAGE_FOUND)
